### PR TITLE
siemens_cp1616 tutorials 

### PR DESCRIPTION
**Pull request by durovsky**
Initial commit 

What's included:
- TIA portal projects for both IO Controller/ IO Device modes
- example yaml config files
- simple C++ code for interfacing PROFINET from ROS

### CODE REVIEW

**Comment by durovsky** [comment]
SINAMIC S120 tutorial added

**Comment by shaun-edwards** [comment]
@durovsky, is there a wiki that goes with these tutorials?

**Comment by durovsky** [comment]
@shaun-edwards, http://wiki.ros.org/siemens_cp1616/Tutorials

**Comment by shaun-edwards** [comment]
+1.

**Pull request merged**
